name: SonarQube Scan

on:
  push:
    branches:
      - main      # or your default branch (e.g., 'master')
  pull_request:
    branches:
      - main      # or your default branch (e.g., 'master')

jobs:
  sonarQube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker
        run: |
          docker --version
          docker-compose --version

      # Step 3: Run SonarQube Docker container
      - name: Start SonarQube container
        run: |
          docker run -d --name sonarqube -p 9000:9000 sonarqube:latest

      # Step 4: Wait for SonarQube to start (you can adjust the wait time if necessary)
      - name: Wait for SonarQube to start
        run: |
          echo "Waiting for SonarQube to start..."
          sleep 30  # Adjust the sleep time if necessary, to give SonarQube time to fully start

      # Step 5: Run SonarScanner Docker container
      - name: Run SonarQube Scan using Docker Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Store your SonarQube token in GitHub Secrets
        run: |
          docker run --rm \
            -v $(pwd):/usr/src \
            -e SONAR_HOST_URL=http://localhost:9000 \
            -e SONAR_LOGIN=$SONAR_TOKEN \
            sonarsource/sonar-scanner-cli:latest
          
      # Step 6: Stop SonarQube container after the scan
      - name: Stop SonarQube container
        run: |
          docker stop sonarqube
